version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    day: monday
    timezone: Asia/Shanghai
  open-pull-requests-limit: 10
  versioning-strategy: lockfile-only