[package]
name = "liquidity-lock-mutator"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.81"
async-trait = "0.1"
ckb-hash = "1"
ckb-jsonrpc-types = "1"
ckb-sdk = "5"
ckb-types = "1"
hex = "0.4.3"
secp256k1 = { version = "0.30.0", features = ["recovery", "global-context"] }
serde = { version = "1.0.197", features = ["derive"] }
serde_json = "1.0.135"

[workspace]
