on: [push, pull_request]

name: Test OpenRPC Spec generating

jobs:
  generating:
    name: Generate OpenRPC Spec
    steps:
      - uses: actions/checkout@v4
      - uses: dsherret/rust-toolchain-file@v1
      - uses: Swatinem/rust-cache@v2
        with:
          key: openrpc-${{ runner.os }}
      - run: |
        cd openrpc-json-generator
        cargo run
